ReMoDy: Bulk Class Reference
Bulk Class Reference
Domain Bulk Properties.
#include <domain.h>
Public Member Functions
REAL Temperature ()
void Temperature (REAL temp)
REAL Volume ()
void Volume (REAL vol)
void init (REAL xmin[], REAL xmax[])
Initializing bulk: setting volume.
Molecule * inject (int specie, REAL velocity, Collection< Molecule > *molecules)
Adding a molecule to the pool with not registering on the grid.
Public Attributes
List< Gas > gases
list of gases initially present in the bulk
Private Attributes
REAL temperature
REAL volume
REAL xmin [DIM]
REAL xmax [DIM]
box-dimensions
Detailed Description
Domain Bulk Properties.
Holds thermodynamics properties and the list of species in the bulk of the domain. Initialized only when the new run. If Run::option.restart=1, it is ingored and the bulk properties and species are retrieved from the input file.
Definition at line 63 of file domain.h.
Member Function Documentation
void Bulk::init (REAL xmin[], REAL xmax[])
Initializing bulk: setting volume.
Definition at line 657 of file domain.cc.
References DIM, volume, xmax, and xmin.
Referenced by Domain::Domain().
Molecule * Bulk::inject (int specie, REAL velocity, Collection< Molecule > * molecules)
Adding a molecule to the pool with not registering on the grid.
Injecting a specie into the bulk with a specified velocity (no registering in the grid).
Definition at line 665 of file domain.cc.
References Collection< Element >::append(), Molecule::Coordinate(), DIM, GAUSS, REAL, RND, Species::Specie::Size(), SMALL, Species::species, Run::time, Molecule::Type(), Molecule::Velocity(), xmax, and xmin.
Referenced by Domain::init().
void Bulk::Temperature (REAL temp) [inline]
Definition at line 69 of file domain.h.
References temperature.
REAL Bulk::Temperature () [inline]
Definition at line 68 of file domain.h.
References temperature.
Referenced by Domain::Domain(), and Domain::init().
void Bulk::Volume (REAL vol) [inline]
Definition at line 71 of file domain.h.
References volume.
REAL Bulk::Volume () [inline]
Definition at line 70 of file domain.h.
References volume.
Referenced by Domain::init().
Member Data Documentation
List<Gas> Bulk::gases
list of gases initially present in the bulk
Definition at line 67 of file domain.h.
Referenced by Domain::Domain(), and Domain::init().
REAL Bulk::temperature [private]
Definition at line 64 of file domain.h.
Referenced by Temperature().
REAL Bulk::volume [private]
Definition at line 64 of file domain.h.
Referenced by init(), and Volume().
REAL Bulk::xmax[DIM] [private]
box-dimensions
Definition at line 64 of file domain.h.
Referenced by init(), and inject().
REAL Bulk::xmin[DIM] [private]
Definition at line 64 of file domain.h.
Referenced by init(), and inject().
The documentation for this class was generated from the following files:
domain.h
domain.cc