ReMoDy: Species::Specie Class Reference
Species::Specie Class Reference
#include <species.h>
Public Member Functions
Specie ()
void Cp (REAL c)
REAL Cp ()
char * Id ()
void Mass (REAL m)
REAL Mass ()
REAL Size ()
void Size (REAL s)
Private Attributes
char id [WORDLENGTH]
REAL mass
REAL size
REAL cp
REAL inertia [DIM]
Detailed Description
Definition at line 6 of file species.h.
Constructor & Destructor Documentation
Species::Specie::Specie () [inline]
Definition at line 13 of file species.h.
References cp, DIM, inertia, mass, and size.
Member Function Documentation
REAL Species::Specie::Cp () [inline]
Definition at line 21 of file species.h.
References cp.
void Species::Specie::Cp (REAL c) [inline]
Definition at line 20 of file species.h.
References cp.
Referenced by Domain::boundary(), Domain::Domain(), Domain::interact(), Domain::run(), and Molecule::Temperature().
char* Species::Specie::Id () [inline]
Definition at line 22 of file species.h.
References id.
Referenced by Domain::Domain(), Domain::init(), Domain::interact(), and Domain::save().
REAL Species::Specie::Mass () [inline]
Definition at line 24 of file species.h.
References mass.
void Species::Specie::Mass (REAL m) [inline]
Definition at line 23 of file species.h.
References mass.
Referenced by Domain::boundary(), Gui::display(), Domain::Domain(), Domain::init(), Domain::injection(), Domain::interact(), Molecule::KineticEnergy(), and Molecule::Move().
void Species::Specie::Size (REAL s) [inline]
Definition at line 26 of file species.h.
References size.
REAL Species::Specie::Size () [inline]
Definition at line 25 of file species.h.
References size.
Referenced by Domain::boundary(), Gui::display(), Domain::Domain(), Bulk::inject(), Boundary::Inject(), Domain::interact(), and Domain::load().
Member Data Documentation
REAL Species::Specie::cp [private]
Definition at line 8 of file species.h.
Referenced by Cp(), and Specie().
char Species::Specie::id[WORDLENGTH] [private]
Definition at line 7 of file species.h.
Referenced by Id().
REAL Species::Specie::inertia[DIM] [private]
Definition at line 8 of file species.h.
Referenced by Specie().
REAL Species::Specie::mass [private]
Definition at line 8 of file species.h.
Referenced by Mass(), and Specie().
REAL Species::Specie::size [private]
Definition at line 8 of file species.h.
Referenced by Size(), and Specie().
The documentation for this class was generated from the following file:
species.h