ReMoDy: Gui Namespace Reference
Gui Namespace Reference
OpenGL window output routines.
Classes
struct ElementDisp
struct ColorScale
struct Scene
struct WindowGeom
Enumerations
enum Elements {
points = 0, nodes, edges, faces,
cells, frame, mesh, boundary_nodes,
boundary_edges, boundary_faces, boundary_cells, maxelements
}
enum Color {
red = 0, green, blue, skyblue,
brown, magenta, yellow, color6,
color7, color8, color9, color10,
color11, color12, color13, color14,
color15, maxcolor
}
enum ColorSchemes {
colorByType = 0, colorByBoundary, colorByTime, colorByMass,
maxColorSchemes
}
enum PointParameters {
variable = maxcolor, vmin, vmax, size,
sizevar, massvar, maxpointprm
}
enum LineParameters { thickness = maxcolor, length, maxlineprm }
enum AxesParameters {
axeswidth = 0, xaxislength, yaxislength, zaxislength,
arrowheight, arrowidth, maxaxesprm
}
enum SurfDispType { gridlines = 0, solidsurface, maxsurfdisptypes }
enum Movement { stay = 0, rotate, moveuv, movew }
enum ShowPars {
showRun = 0, showAxes, showSpheres, showBonds,
showGrid, showNodes, showVariables, showBoundaryVertexes,
showBoundaryVectors, showToolVertexes, showBoundaryFaceCenters, showBoundaryFaces,
showBoundaryGrid, showToolGrid, showFrame, showCellCenters,
showFaceCenters, showIsoSurfaces, dumpWindow, maxshowpars
}
Functions
int query_extension (char *extName)
void init (int argc, char *argv[], Domain *newdomain)
void helpDisplay ()
int readparam (char *s, char *param[], int maxparam, char *filename, int val[])
int readparam (char *s, char *param[], int maxparam, char *filename, REAL val[])
void readconf ()
void refresh ()
void initdisp ()
void Materials (int argc, char *argv[])
void showVector (double *x, double *v)
void showParticle (double vmn, double vmx, double val, double *x)
void showSphere (double vmn, double vmx, double val, double rad, double *x)
void displayAxes ()
void getScaling (double &l0, double &l1)
void getXLimits (double *x0, double *x1)
void Exit ()
void Quit ()
void menu (int value)
void displayMenu ()
void consoleMenu ()
void setBackgroundRun ()
void setForegroundRun ()
void toggleSpheres ()
void switchColorScheme ()
void runmany ()
void toggleWindowDump ()
void dumpwindow ()
void commandMode ()
void display ()
void animate ()
void helpCommand ()
void reshape (int w, int h)
void mouse (int button, int state, int x, int y)
void motion (int x, int y)
void keyboard (unsigned int key)
void run ()
void displaymessage (char *msg)
void setElementColor (int element_type, REAL rgbcolor[])
void getElementColor (int element_type, REAL rgbcolor[])
void writeData ()
void printGridXLimits ()
void printGridVecLimits ()
void getXLimits (REAL *xmin, REAL *xmax)
void getScaling (REAL &lmin, REAL &lmax)
void printPartVelLimits ()
void printParticleVariables ()
void showGridElements (int ne, double *X, REAL color[])
void showVectorComponent (int ivar, int icomp, double *X, double vmn, double vmx)
void showVector (int ivar, double *X)
void printVariables (int n)
void finish ()
void InitMaterials (void)
void selectVariable ()
void keyboard (unsigned char key, int x, int y)
void drawSegment (REAL *x, REAL *y)
Variables
Domain * domain
ElementDisp disp [maxelements]
char * configfile = (char*)"gui.cfg"
char windowname [MAXLINLEN]
int showpar [maxshowpars]
int finished
int animation
int nwdump
int iwdump
int attributeList []
REAL step
REAL vecval [maxlineprm]
REAL axes [maxaxesprm]
REAL rgbcolor [maxcolor][3]
REAL wdtime
REAL xo [3]
REAL dx
REAL dy
REAL dz
REAL lastx
REAL lasty
REAL lastz
int mouseButtons [3]
REAL zoom
REAL rotx
REAL roty
REAL tx
REAL ty
REAL xmin [DIM]
REAL xmax [DIM]
REAL lx
REAL ly
REAL lz
REAL lmin
REAL lmax
enum Movement movement
struct ColorScale colorscale
struct Scene scene
struct WindowGeom window
struct BFaceList * bface_root
Display * dpy
Window win
int firstR = 1
int * vars
int * coms
Detailed Description
OpenGL window output routines.
Enumeration Type Documentation
enum Gui::AxesParameters
Enumerator:
axeswidth
xaxislength
yaxislength
zaxislength
arrowheight
arrowidth
maxaxesprm
Definition at line 71 of file gui.h.
enum Gui::Color
Enumerator:
red
green
blue
skyblue
brown
magenta
yellow
color6
color7
color8
color9
color10
color11
color12
color13
color14
color15
maxcolor
Definition at line 31 of file gui.h.
enum Gui::ColorSchemes
Enumerator:
colorByType
colorByBoundary
colorByTime
colorByMass
maxColorSchemes
Definition at line 51 of file gui.h.
enum Gui::Elements
Enumerator:
points
nodes
edges
faces
cells
frame
mesh
boundary_nodes
boundary_edges
boundary_faces
boundary_cells
maxelements
Definition at line 17 of file gui.h.
enum Gui::LineParameters
Enumerator:
thickness
length
maxlineprm
Definition at line 65 of file gui.h.
enum Gui::Movement
Enumerator:
stay
rotate
moveuv
movew
Definition at line 123 of file gui.h.
enum Gui::PointParameters
Enumerator:
variable
vmin
vmax
size
sizevar
massvar
maxpointprm
Definition at line 58 of file gui.h.
enum Gui::ShowPars
Enumerator:
showRun
showAxes
showSpheres
showBonds
showGrid
showNodes
showVariables
showBoundaryVertexes
showBoundaryVectors
showToolVertexes
showBoundaryFaceCenters
showBoundaryFaces
showBoundaryGrid
showToolGrid
showFrame
showCellCenters
showFaceCenters
showIsoSurfaces
dumpWindow
maxshowpars
Definition at line 129 of file gui.h.
enum Gui::SurfDispType
Enumerator:
gridlines
solidsurface
maxsurfdisptypes
Definition at line 81 of file gui.h.
Function Documentation
void Gui::animate ()
DDD glutIdleFunc(NULL);//Causes segmentation fault (!?)
refresh();
Definition at line 1851 of file gui.cc.
References animation, display(), domain, dumpwindow(), dumpWindow, ESC, finished, iwdump, nwdump, Run::option, Domain::run(), showpar, showRun, and Run::time.
Referenced by menu().
void Gui::commandMode ()
Definition at line 1465 of file gui.cc.
References consoleMenu(), dumpwindow(), Exit(), helpCommand(), MAXLINLEN, Quit(), runmany(), setBackgroundRun(), setForegroundRun(), switchColorScheme(), toggleSpheres(), and toggleWindowDump().
Referenced by keyboard().
void Gui::consoleMenu ()
Definition at line 1360 of file gui.cc.
References displayMenu(), MAXLINLEN, and menu().
Referenced by commandMode(), and keyboard().
void Gui::display ()
Definition at line 1530 of file gui.cc.
References blue, Gui::Scene::color, colorByBoundary, colorByMass, colorByTime, colorByType, Molecule::Coordinates(), Collection< Element >::Current(), displayAxes(), domain, dpy, faces, Gui::Scene::frame, frame, getElementColor(), Collection< Element >::goFirst(), Collection< Element >::goNext(), green, init(), Collection< Element >::isFirst(), Potential::lengthscale(), Gui::Scene::Scene::Frame::line, Species::Specie::Mass(), Gui::Scene::Scene::Color::maxvalue, Gui::Scene::mesh, Gui::Scene::Scene::Color::minvalue, Domain::Molecules(), Gui::Scene::Scene::Mesh::node, nodes, Collection< Element >::number(), Run::option, Palette::pickcolor(), REAL, red, refresh(), rotx, roty, scene, Gui::Scene::Scene::Color::scheme, showBoundaryGrid, showBoundaryVertexes, showFrame, showGrid, showNodes, showpar, showSpheres, Species::Specie::Size(), size, Species::species, thickness, Run::time, tx, ty, Molecule::Type(), win, xmax, xmin, and zoom.
Referenced by animate().
void Gui::displayAxes ()
Definition at line 1181 of file gui.cc.
References arrowheight, arrowidth, axes, axeswidth, lx, ly, lz, showAxes, showpar, xaxislength, xo, yaxislength, and zaxislength.
Referenced by display().
void Gui::displayMenu ()
Definition at line 1334 of file gui.cc.
Referenced by consoleMenu().
void Gui::displaymessage (char * msg)
Definition at line 2162 of file gui.cc.
void Gui::drawSegment (REAL * x, REAL * y)
void Gui::dumpwindow ()
Definition at line 1461 of file gui.cc.
References windowname, and IO::xwd().
Referenced by animate(), and commandMode().
void Gui::Exit ()
Definition at line 1229 of file gui.cc.
References animation, and MAXLINLEN.
Referenced by commandMode(), and keyboard().
void Gui::finish ()
void Gui::getElementColor (int element_type, REAL rgbcolor[])
Definition at line 2172 of file gui.cc.
References disp, and maxelements.
Referenced by display().
void Gui::getScaling (REAL & lmin, REAL & lmax)
void Gui::getScaling (double & l0, double & l1)
Definition at line 1212 of file gui.cc.
References lmax, and lmin.
Referenced by reshape().
void Gui::getXLimits (REAL * xmin, REAL * xmax)
void Gui::getXLimits (double * x0, double * x1)
Definition at line 1220 of file gui.cc.
References xmax, and xmin.
void Gui::helpCommand ()
Definition at line 1871 of file gui.cc.
References Run::outputname.
Referenced by commandMode().
void Gui::helpDisplay ()
Definition at line 175 of file gui.cc.
References configfile, and Run::outputname.
Referenced by init(), keyboard(), and menu().
void Gui::init (int argc, char * argv[], Domain * newdomain)
Definition at line 91 of file gui.cc.
References animation, attributeList, Gui::Scene::color, colorByMass, domain, dpy, dumpWindow, ERROR, finished, Gui::WindowGeom::height, helpDisplay(), initdisp(), lastx, lasty, lastz, Materials(), mouseButtons, Run::option, query_extension(), rotx, roty, scene, Gui::Scene::Scene::Color::scheme, showAxes, showBonds, showBoundaryFaceCenters, showBoundaryFaces, showBoundaryGrid, showBoundaryVectors, showBoundaryVertexes, showCellCenters, showFaceCenters, showFrame, showGrid, showNodes, showpar, showRun, showSpheres, showToolGrid, showToolVertexes, showVariables, tx, ty, wdtime, Gui::WindowGeom::width, win, window, windowname, and zoom.
Referenced by display(), and main().
void Gui::initdisp ()
DDD
Definition at line 701 of file gui.cc.
References arrowheight, arrowidth, axes, axeswidth, blue, brown, cells, colorscale, DIM, domain, dx, dy, dz, edges, faces, frame, Gui::Scene::frame, green, Gui::WindowGeom::height, LARGE, length, Gui::Scene::Scene::Mesh::line, Gui::Scene::Scene::Frame::line, lmax, lmin, lx, ly, lz, magenta, MAX_WINDOW_HEIGHT, MAX_WINDOW_WIDTH, maxcolor, maxelements, mesh, Gui::Scene::mesh, Domain::Molecules(), Gui::Scene::Scene::Mesh::node, nodes, Collection< Element >::number(), Run::option, readconf(), REAL, red, Gui::ColorScale::relative, rgbcolor, scene, setElementColor(), Domain::setMaxBound(), Domain::setMinBound(), size, skyblue, step, thickness, vecval, Gui::WindowGeom::width, window, WINDOW_SIZE, xaxislength, xmax, xmin, xo, yaxislength, yellow, zaxislength, and zoom.
Referenced by init().
void Gui::InitMaterials (void)
void Gui::keyboard (unsigned char key, int x, int y)
void Gui::keyboard (unsigned int key)
refresh();
Definition at line 1978 of file gui.cc.
References animation, commandMode(), consoleMenu(), domain, ESC, Exit(), finished, helpDisplay(), MAXLINLEN, Run::option, Run::outputname, readconf(), Domain::run(), Domain::save(), showAxes, showBoundaryFaces, showBoundaryGrid, showBoundaryVectors, showBoundaryVertexes, showFrame, showGrid, showNodes, showpar, switchColorScheme(), Run::time, and zoom.
void Gui::Materials (int argc, char * argv[])
Definition at line 818 of file gui.cc.
References lz, Run::option, and xo.
Referenced by init().
void Gui::menu (int value)
Definition at line 1253 of file gui.cc.
References ABOUT, animate(), animation, finished, helpDisplay(), showAxes, showBonds, showBoundaryFaceCenters, showBoundaryGrid, showBoundaryVectors, showBoundaryVertexes, showCellCenters, showFaceCenters, showGrid, showNodes, showpar, and showVariables.
Referenced by consoleMenu().
void Gui::motion (int x, int y)
Definition at line 1954 of file gui.cc.
References lastx, lasty, mouseButtons, REAL, rotx, roty, tx, ty, and zoom.
void Gui::mouse (int button, int state, int x, int y)
Definition at line 1927 of file gui.cc.
References lastx, lasty, LEFT_BUTTON, MIDDLE_BUTTON, mouseButtons, and RIGHT_BUTTON.
void Gui::printGridVecLimits ()
void Gui::printGridXLimits ()
void Gui::printParticleVariables ()
void Gui::printPartVelLimits ()
void Gui::printVariables (int n)
int Gui::query_extension (char * extName)
Definition at line 78 of file gui.cc.
Referenced by init().
void Gui::Quit ()
Definition at line 1241 of file gui.cc.
References animation, and MAXLINLEN.
Referenced by commandMode().
void Gui::readconf ()
Definition at line 259 of file gui.cc.
References arrowheight, arrowidth, axeswidth, blue, brown, Gui::Scene::color, colorByMass, colorByType, Run::configfile, configfile, DIM, DOCTYPE, domain, dx, dy, dz, frame, Gui::Scene::frame, green, length, Gui::Scene::Scene::Frame::line, Gui::Scene::Scene::Mesh::line, lx, ly, lz, magenta, massvar, maxaxesprm, Domain::maxBound(), maxcolor, maxlineprm, MAXLINLEN, maxpointprm, maxshowpars, Gui::Scene::Scene::Color::maxvalue, mesh, Gui::Scene::mesh, Domain::minBound(), Gui::Scene::Scene::Color::minvalue, Gui::Scene::Scene::Mesh::node, nodes, Run::option, IO::parseWord(), REAL, red, rgbcolor, scene, Gui::Scene::Scene::Color::scheme, setElementColor(), showpar, showSpheres, size, sizevar, skyblue, step, thickness, variable, vecval, vmax, vmin, xaxislength, xmax, xmin, yaxislength, and zaxislength.
Referenced by initdisp(), and keyboard().
int Gui::readparam (char * s, char * param[], int maxparam, char * filename, REAL val[])
Definition at line 230 of file gui.cc.
int Gui::readparam (char * s, char * param[], int maxparam, char * filename, int val[])
Definition at line 198 of file gui.cc.
void Gui::refresh ()
Definition at line 689 of file gui.cc.
Referenced by display().
void Gui::reshape (int w, int h)
Definition at line 1890 of file gui.cc.
References getScaling(), lmax, and lmin.
void Gui::run ()
Definition at line 2159 of file gui.cc.
Referenced by main().
void Gui::runmany ()
Definition at line 1392 of file gui.cc.
References domain, and Domain::run().
Referenced by commandMode().
void Gui::selectVariable ()
void Gui::setBackgroundRun ()
Definition at line 1376 of file gui.cc.
References showpar, and showRun.
Referenced by commandMode().
void Gui::setElementColor (int element_type, REAL rgbcolor[])
Definition at line 2166 of file gui.cc.
References disp, and maxelements.
Referenced by initdisp(), and readconf().
void Gui::setForegroundRun ()
Definition at line 1380 of file gui.cc.
References showpar, and showRun.
Referenced by commandMode().
void Gui::showGridElements (int ne, double * X, REAL color[])
void Gui::showParticle (double vmn, double vmx, double val, double * x)
Definition at line 952 of file gui.cc.
References PI, REAL, and Palette::vav.
void Gui::showSphere (double vmn, double vmx, double val, double rad, double * x)
= { 0.6, 0.8, 0.3, 1.0 },
Definition at line 982 of file gui.cc.
References PI, REAL, and Palette::vav.
void Gui::showVector (int ivar, double * X)
void Gui::showVector (double * x, double * v)
Definition at line 874 of file gui.cc.
References length, and vecval.
void Gui::showVectorComponent (int ivar, int icomp, double * X, double vmn, double vmx)
void Gui::switchColorScheme ()
Definition at line 1388 of file gui.cc.
References Gui::Scene::color, maxColorSchemes, scene, and Gui::Scene::Scene::Color::scheme.
Referenced by commandMode(), and keyboard().
void Gui::toggleSpheres ()
Definition at line 1384 of file gui.cc.
References showpar, and showSpheres.
Referenced by commandMode().
void Gui::toggleWindowDump ()
Definition at line 1448 of file gui.cc.
References dumpWindow, iwdump, nwdump, showpar, step, Run::time, and wdtime.
Referenced by commandMode().
void Gui::writeData ()
Variable Documentation
int Gui::animation
Definition at line 29 of file gui.cc.
Referenced by animate(), Exit(), init(), keyboard(), menu(), and Quit().
int Gui::attributeList[]
Initial value:
                {       GLX_RGBA,
                        GLX_RED_SIZE, 1,
                        GLX_GREEN_SIZE, 1,
                        GLX_BLUE_SIZE, 1,
                        GLX_DOUBLEBUFFER,
                        GLX_DEPTH_SIZE, 1,
                        None
                }
Definition at line 33 of file gui.cc.
Referenced by init().
REAL Gui::axes ()
Definition at line 43 of file gui.cc.
Referenced by displayAxes(), and initdisp().
struct BFaceList* Gui::bface_root
Definition at line 70 of file gui.cc.
struct ColorScale Gui::colorscale
Definition at line 66 of file gui.cc.
Referenced by initdisp().
int * Gui::coms
Definition at line 76 of file gui.cc.
char * Gui::configfile = (char*)"gui.cfg"
Definition at line 26 of file gui.cc.
Referenced by helpDisplay(), and readconf().
ElementDisp Gui::disp
Definition at line 25 of file gui.cc.
Referenced by getElementColor(), and setElementColor().
Domain* Gui::domain
Definition at line 24 of file gui.cc.
Referenced by animate(), display(), init(), initdisp(), keyboard(), main(), readconf(), and runmany().
Display* Gui::dpy
Definition at line 72 of file gui.cc.
Referenced by display(), and init().
REAL Gui::dx
Definition at line 43 of file gui.cc.
Referenced by Domain::boundary(), initdisp(), Boundary::Inject(), Domain::interact(), Domain::interaction(), and readconf().
REAL Gui::dy
Definition at line 43 of file gui.cc.
Referenced by initdisp(), and readconf().
REAL Gui::dz
Definition at line 43 of file gui.cc.
Referenced by initdisp(), and readconf().
int Gui::finished
Definition at line 29 of file gui.cc.
Referenced by animate(), init(), keyboard(), and menu().
int Gui::firstR = 1
Definition at line 75 of file gui.cc.
int Gui::iwdump
Definition at line 29 of file gui.cc.
Referenced by animate(), and toggleWindowDump().
REAL Gui::lastx
Definition at line 43 of file gui.cc.
Referenced by init(), motion(), and mouse().
REAL Gui::lasty
Definition at line 43 of file gui.cc.
Referenced by init(), motion(), and mouse().
REAL Gui::lastz
Definition at line 43 of file gui.cc.
Referenced by init().
REAL Gui::lmax
Definition at line 61 of file gui.cc.
Referenced by getScaling(), initdisp(), and reshape().
REAL Gui::lmin
Definition at line 61 of file gui.cc.
Referenced by getScaling(), initdisp(), and reshape().
REAL Gui::lx
Definition at line 61 of file gui.cc.
Referenced by displayAxes(), initdisp(), and readconf().
REAL Gui::ly
Definition at line 61 of file gui.cc.
Referenced by displayAxes(), initdisp(), and readconf().
REAL Gui::lz
Definition at line 61 of file gui.cc.
Referenced by displayAxes(), initdisp(), Materials(), and readconf().
int Gui::mouseButtons
Definition at line 53 of file gui.cc.
Referenced by init(), motion(), and mouse().
enum Movement Gui::movement
Definition at line 64 of file gui.cc.
int Gui::nwdump
Definition at line 29 of file gui.cc.
Referenced by animate(), and toggleWindowDump().
REAL Gui::rgbcolor ()
Definition at line 43 of file gui.cc.
Referenced by initdisp(), and readconf().
REAL Gui::rotx
Definition at line 55 of file gui.cc.
Referenced by display(), init(), and motion().
REAL Gui::roty
Definition at line 56 of file gui.cc.
Referenced by display(), init(), and motion().
struct Scene Gui::scene
Definition at line 67 of file gui.cc.
Referenced by display(), init(), initdisp(), readconf(), and switchColorScheme().
int Gui::showpar
Definition at line 29 of file gui.cc.
Referenced by animate(), display(), displayAxes(), init(), keyboard(), menu(), readconf(), setBackgroundRun(), setForegroundRun(), toggleSpheres(), and toggleWindowDump().
REAL Gui::step
Definition at line 43 of file gui.cc.
Referenced by initdisp(), readconf(), and toggleWindowDump().
REAL Gui::tx
Definition at line 57 of file gui.cc.
Referenced by display(), init(), and motion().
REAL Gui::ty
Definition at line 58 of file gui.cc.
Referenced by display(), init(), and motion().
int* Gui::vars
Definition at line 76 of file gui.cc.
REAL Gui::vecval ()
Definition at line 43 of file gui.cc.
Referenced by initdisp(), readconf(), and showVector().
REAL Gui::wdtime
Definition at line 43 of file gui.cc.
Referenced by init(), and toggleWindowDump().
Window Gui::win
Definition at line 73 of file gui.cc.
Referenced by display(), and init().
struct WindowGeom Gui::window
Definition at line 68 of file gui.cc.
Referenced by init(), and initdisp().
char Gui::windowname[MAXLINLEN]
Definition at line 26 of file gui.cc.
Referenced by dumpwindow(), and init().
REAL Gui::xmax ()
Definition at line 61 of file gui.cc.
Referenced by display(), Domain::Domain(), getXLimits(), initdisp(), and readconf().
REAL Gui::xmin
Definition at line 61 of file gui.cc.
Referenced by display(), Domain::Domain(), getXLimits(), initdisp(), and readconf().
REAL Gui::xo
Definition at line 43 of file gui.cc.
Referenced by displayAxes(), initdisp(), and Materials().
REAL Gui::zoom
Definition at line 54 of file gui.cc.
Referenced by display(), init(), initdisp(), keyboard(), and motion().