ReMoDy: IO Namespace Reference
IO Namespace Reference
Some IO routines.
Functions
void initxwd (int i)
void xwd (char *windowname)
int getCharAttr (xmlNodePtr cur, char *attr, char *result)
int getIntAttr (xmlNodePtr cur, char *attr)
int getIntAttr (xmlDocPtr doc, char *tag, char *keyname, char *key, char *attr)
int parseWord (xmlDocPtr doc, xmlNodePtr cur, char *keyword, char *result)
int parseInt (xmlDocPtr doc, xmlNodePtr cur, char *keyword)
int parseFloat (xmlDocPtr doc, xmlNodePtr cur, char *keyword, REAL &result)
double parseFloat (xmlDocPtr doc, xmlNodePtr cur, char *keyword)
void getTimeXML (char inpfilename[])
void getTime (char inpfilename[])
int getIter (char inpfilename[])
Variables
int ioutput = 0
int nxwdump = 0
Detailed Description
Some IO routines.
Function Documentation
int IO::getCharAttr (xmlNodePtr cur, char * attr, char * result)
Definition at line 40 of file io.cc.
References MAXLINLEN, and Run::option.
Referenced by Domain::Domain(), and getIntAttr().
int IO::getIntAttr (xmlDocPtr doc, char * tag, char * keyname, char * key, char * attr)
xmlChar *key;
val=getIntAttr(cur,attr);
Definition at line 77 of file io.cc.
References getCharAttr(), MAXLINLEN, Run::option, parseInt(), and Potential::value().
int IO::getIntAttr (xmlNodePtr cur, char * attr)
Definition at line 57 of file io.cc.
References Run::option.
int IO::getIter (char inpfilename[])
Definition at line 249 of file io.cc.
References DOCTYPE, MAXLINLEN, and Run::option.
Referenced by main().
void IO::getTime (char inpfilename[])
Definition at line 239 of file io.cc.
References getTimeXML(), Run::option, and Run::time.
Referenced by Run::init().
void IO::getTimeXML (char inpfilename[])
Definition at line 198 of file io.cc.
References DOCTYPE, MAXLINLEN, parseFloat(), and Run::time.
Referenced by getTime().
void IO::initxwd (int i)
Definition at line 15 of file io.cc.
References nxwdump.
double IO::parseFloat (xmlDocPtr doc, xmlNodePtr cur, char * keyword)
Definition at line 178 of file io.cc.
References Run::option.
Referenced by Domain::Domain().
int IO::parseFloat (xmlDocPtr doc, xmlNodePtr cur, char * keyword, REAL & result)
Definition at line 158 of file io.cc.
References Run::option, and REAL.
Referenced by getTimeXML().
int IO::parseInt (xmlDocPtr doc, xmlNodePtr cur, char * keyword)
Definition at line 138 of file io.cc.
References Run::option.
Referenced by getIntAttr().
int IO::parseWord (xmlDocPtr doc, xmlNodePtr cur, char * keyword, char * result)
Definition at line 117 of file io.cc.
References MAXLINLEN, and Run::option.
Referenced by Domain::Domain(), and Gui::readconf().
void IO::xwd (char * windowname)
Definition at line 19 of file io.cc.
References MAXLINLEN, nxwdump, and Run::option.
Referenced by Gui::dumpwindow().
Variable Documentation
int IO::ioutput = 0
Definition at line 13 of file io.cc.
Referenced by Domain::load(), Domain::run(), and Domain::save().
int IO::nxwdump = 0
Definition at line 14 of file io.cc.
Referenced by initxwd(), and xwd().