ReMoDy: Potential Namespace Reference
Potential Namespace Reference
Interaction-potential functions, such as LJ.
Functions
REAL invdist (REAL x)
void strength (REAL strength)
REAL strength ()
void lengthscale (REAL lengthscale)
REAL lengthscale ()
void Cutoff (REAL newcutoff)
REAL Cutoff ()
REAL value (REAL r)
REAL force (REAL r)
REAL derivative (REAL r)
Variables
REAL sigma = 1.0
REAL eta = 1.0
REAL cutoff = 2.0
const REAL small = 1.0e-20
const REAL large = 1.0e20
Detailed Description
Interaction-potential functions, such as LJ.
Function Documentation
REAL Potential::Cutoff () [inline]
Definition at line 154 of file model.h.
References cutoff.
Referenced by Domain::load().
void Potential::Cutoff (REAL newcutoff) [inline]
Definition at line 153 of file model.h.
References cutoff.
REAL Potential::derivative (REAL r)
REAL Potential::force (REAL r) [inline]
Definition at line 166 of file model.h.
References eta, and sigma.
REAL Potential::invdist (REAL x)
Definition at line 102 of file model.cc.
REAL Potential::lengthscale () [inline]
Definition at line 152 of file model.h.
References sigma.
Referenced by Gui::display(), and Domain::Domain().
void Potential::lengthscale (REAL lengthscale) [inline]
Definition at line 149 of file model.h.
References sigma.
Referenced by Domain::load().
REAL Potential::strength () [inline]
Definition at line 148 of file model.h.
References eta.
Referenced by Domain::Domain().
void Potential::strength (REAL strength) [inline]
Definition at line 145 of file model.h.
References eta.
REAL Potential::value (REAL r) [inline]
Definition at line 155 of file model.h.
References cutoff, eta, large, REAL, sigma, and small.
Referenced by IO::getIntAttr().
Variable Documentation
REAL Potential::cutoff = 2.0
Definition at line 85 of file model.cc.
Referenced by Cutoff(), and value().
REAL Potential::eta = 1.0
Definition at line 85 of file model.cc.
Referenced by force(), strength(), and value().
const REAL Potential::large = 1.0e20
Definition at line 142 of file model.h.
Referenced by value().
REAL Potential::sigma = 1.0
Definition at line 85 of file model.cc.
Referenced by force(), lengthscale(), and value().
const REAL Potential::small = 1.0e-20
Definition at line 142 of file model.h.
Referenced by value().