ReMoDy: Species::Reaction::Reaction::Outcome Struct Reference
Species::Reaction::Reaction::Outcome Struct Reference
Possible outcomes of a reaction.
#include <species.h>
Public Member Functions
Outcome ()
Outcome (int ip0, int ip1, REAL a, REAL p, REAL h)
void Products (int ip0, int ip1)
int Product (int i)
void Time (REAL t)
REAL Time ()
void ActivationEnergy (REAL a)
REAL ActivationEnergy ()
void Probability (REAL r)
REAL Probability ()
void Enthalpy (REAL h)
REAL Enthalpy ()
Public Attributes
int product [2]
two indexes of the products of a reaction
REAL activationEnergy
REAL probability
REAL enthalpy
REAL time
Outcome * next
linked list of outcomes
Detailed Description
Possible outcomes of a reaction.
Definition at line 37 of file species.h.
Constructor & Destructor Documentation
Species::Reaction::Reaction::Outcome::Outcome () [inline]
Definition at line 44 of file species.h.
References Species::Reaction::Reaction::Outcome::enthalpy, Species::Reaction::Reaction::Outcome::next, Species::Reaction::Reaction::Outcome::probability, Species::Reaction::Reaction::Outcome::product, Species::Reaction::Reaction::Outcome::time, and VOIDSPECIE.
Species::Reaction::Reaction::Outcome::Outcome (int ip0, int ip1, REAL a, REAL p, REAL h) [inline]
Parameters:
ip0 index of the first reaction product
ip1 index of the second reaction product
a activation energy
p outcome probability
h enthalpy of reaction
Definition at line 49 of file species.h.
References Species::Reaction::Reaction::Outcome::activationEnergy, Species::Reaction::Reaction::Outcome::enthalpy, Species::Reaction::Reaction::Outcome::next, Species::nspecies, Species::Reaction::Reaction::Outcome::probability, Species::Reaction::Reaction::Outcome::product, and Species::Reaction::Reaction::Outcome::time.
Member Function Documentation
REAL Species::Reaction::Reaction::Outcome::ActivationEnergy () [inline]
Definition at line 120 of file species.h.
References Species::Reaction::Reaction::Outcome::activationEnergy.
void Species::Reaction::Reaction::Outcome::ActivationEnergy (REAL a) [inline]
Definition at line 119 of file species.h.
References Species::Reaction::Reaction::Outcome::activationEnergy.
Referenced by Domain::interact().
REAL Species::Reaction::Reaction::Outcome::Enthalpy () [inline]
Definition at line 124 of file species.h.
References Species::Reaction::Reaction::Outcome::enthalpy.
void Species::Reaction::Reaction::Outcome::Enthalpy (REAL h) [inline]
Definition at line 123 of file species.h.
References Species::Reaction::Reaction::Outcome::enthalpy.
Referenced by Domain::boundary(), Domain::Domain(), and Domain::interact().
REAL Species::Reaction::Reaction::Outcome::Probability () [inline]
Definition at line 122 of file species.h.
References Species::Reaction::Reaction::Outcome::probability.
void Species::Reaction::Reaction::Outcome::Probability (REAL r) [inline]
Definition at line 121 of file species.h.
References Species::Reaction::Reaction::Outcome::probability.
Referenced by Domain::boundary(), Domain::Domain(), and Domain::interact().
int Species::Reaction::Reaction::Outcome::Product (int i) [inline]
Definition at line 110 of file species.h.
References Species::Reaction::Reaction::Outcome::product.
Referenced by Domain::boundary(), Domain::Domain(), and Domain::interact().
void Species::Reaction::Reaction::Outcome::Products (int ip0, int ip1) [inline]
Definition at line 98 of file species.h.
References Species::Reaction::Reaction::Outcome::product.
REAL Species::Reaction::Reaction::Outcome::Time () [inline]
Definition at line 118 of file species.h.
References Species::Reaction::Reaction::Outcome::time.
void Species::Reaction::Reaction::Outcome::Time (REAL t) [inline]
Definition at line 117 of file species.h.
References Species::Reaction::Reaction::Outcome::time.
Referenced by Domain::boundary().
Member Data Documentation
REAL Species::Reaction::Reaction::Outcome::activationEnergy
Definition at line 39 of file species.h.
Referenced by Species::Reaction::Reaction::Outcome::ActivationEnergy(), and Species::Reaction::Reaction::Outcome::Outcome().
REAL Species::Reaction::Reaction::Outcome::enthalpy
Definition at line 39 of file species.h.
Referenced by Species::Reaction::Reaction::Outcome::Enthalpy(), and Species::Reaction::Reaction::Outcome::Outcome().
Outcome* Species::Reaction::Reaction::Outcome::next
linked list of outcomes
Definition at line 43 of file species.h.
Referenced by Species::Reaction::Add(), Species::Reaction::Erase(), Species::Reaction::Next(), and Species::Reaction::Reaction::Outcome::Outcome().
REAL Species::Reaction::Reaction::Outcome::probability
Definition at line 39 of file species.h.
Referenced by Species::Reaction::Reaction::Outcome::Outcome(), and Species::Reaction::Reaction::Outcome::Probability().
int Species::Reaction::Reaction::Outcome::product[2]
two indexes of the products of a reaction
Definition at line 38 of file species.h.
Referenced by Species::Reaction::Reaction::Outcome::Outcome(), Species::Reaction::Reaction::Outcome::Product(), and Species::Reaction::Reaction::Outcome::Products().
REAL Species::Reaction::Reaction::Outcome::time
time of reaction: used primarily for surface reactions, where there is a time delay between species adsorption on the surface and product formation.
Definition at line 39 of file species.h.
Referenced by Species::Reaction::Reaction::Outcome::Outcome(), and Species::Reaction::Reaction::Outcome::Time().
The documentation for this struct was generated from the following file:
species.h