ReMoDy: Species::Reaction Struct Reference
Species::Reaction Struct Reference
Reaction determines the two products only.
#include <species.h>
Classes
struct Outcome
Possible outcomes of a reaction.
Public Member Functions
Reaction ()
~Reaction ()
void Erase (Outcome *outcome)
void Add (int ip0, int ip1, REAL a, REAL p, REAL h)
Outcome * First ()
Outcome * Next ()
Public Attributes
struct Species::Reaction::Outcome * outcomes
Possible outcomes of a reaction.
struct Species::Reaction::Outcome * current
all outcomes, and the current outcome
Detailed Description
Reaction determines the two products only.
Definition at line 35 of file species.h.
Constructor & Destructor Documentation
Species::Reaction::Reaction () [inline]
Definition at line 126 of file species.h.
References current, and outcomes.
Species::Reaction::~Reaction () [inline]
Definition at line 127 of file species.h.
References Erase(), and outcomes.
Member Function Documentation
void Species::Reaction::Add (int ip0, int ip1, REAL a, REAL p, REAL h) [inline]
Add reaction products, probability, and enthalpy:
Definition at line 135 of file species.h.
References Species::Reaction::Reaction::Outcome::next, and outcomes.
Referenced by Domain::Domain().
void Species::Reaction::Erase (Outcome * outcome) [inline]
Definition at line 131 of file species.h.
References Species::Reaction::Reaction::Outcome::next.
Referenced by ~Reaction().
Outcome* Species::Reaction::First () [inline]
Definition at line 157 of file species.h.
References current, and outcomes.
Referenced by Domain::boundary(), Domain::Domain(), and Domain::interact().
Outcome* Species::Reaction::Next () [inline]
Definition at line 158 of file species.h.
References current, Species::Reaction::Reaction::Outcome::next, and outcomes.
Referenced by Domain::boundary(), Domain::Domain(), and Domain::interact().
Member Data Documentation
struct Species::Reaction::Outcome* Species::Reaction::current
all outcomes, and the current outcome
Referenced by First(), Next(), and Reaction().
struct Species::Reaction::Outcome * Species::Reaction::outcomes
Possible outcomes of a reaction.
Referenced by Add(), First(), Next(), Reaction(), and ~Reaction().
The documentation for this struct was generated from the following file:
species.h