ReMoDy: Molecule Class Reference
Molecule Class Reference
#include <model.h>
Public Member Functions
Molecule ()
void Type (int t)
int Type ()
void InternalEnergy (REAL e)
REAL InternalEnergy ()
REAL Coordinate (int i)
void Coordinate (int i, REAL y)
REAL * Coordinates ()
void Coordinates (REAL y[])
void setCoordinates (REAL y[])
REAL Velocity (int i)
void Velocity (int i, REAL u)
REAL * Velocity ()
void Velocity (REAL u[])
void setVelocity (REAL u[])
REAL KineticEnergy ()
Retrieve kinetic energy.
void Temperature (REAL temperature)
Set internal energy according to temperature:.
void Move ()
Moving a molecule by one time step.
void copy (Molecule *molecule)
Private Attributes
int type
points to the species[type];
REAL energy
internal energy
REAL x [DIM]
position of center of mass
REAL v [DIM]
velocity of center of mass
Detailed Description
Definition at line 23 of file model.h.
Constructor & Destructor Documentation
Molecule::Molecule ()
Definition at line 20 of file model.cc.
References energy, Run::time, and type.
Member Function Documentation
void Molecule::Coordinate (int i, REAL y) [inline]
Definition at line 103 of file model.h.
References DIM, and x.
REAL Molecule::Coordinate (int i) [inline]
Definition at line 95 of file model.h.
References DIM, and x.
Referenced by copy(), Bulk::inject(), Boundary::Inject(), Domain::load(), and Domain::save().
void Molecule::Coordinates (REAL y[]) [inline]
Definition at line 111 of file model.h.
References DIM, and x.
REAL* Molecule::Coordinates () [inline]
Definition at line 110 of file model.h.
References x.
Referenced by Domain::boundary(), Domain::computeBounds(), Gui::display(), Domain::interact(), and GridContainer::put().
void Molecule::copy (Molecule * molecule)
Definition at line 36 of file model.cc.
References Coordinate(), DIM, Type(), type, v, Velocity(), and x.
REAL Molecule::InternalEnergy () [inline]
Definition at line 86 of file model.h.
References energy.
Referenced by Temperature().
void Molecule::InternalEnergy (REAL e) [inline]
Definition at line 85 of file model.h.
References energy.
Referenced by Domain::boundary(), Domain::interact(), Domain::load(), Domain::run(), and Domain::save().
REAL Molecule::KineticEnergy ()
Retrieve kinetic energy.
Definition at line 46 of file model.cc.
References DIM, Species::Specie::Mass(), REAL, Species::species, type, and v.
Referenced by Domain::boundary(), and Domain::run().
void Molecule::Move ()
Moving a molecule by one time step.
Definition at line 68 of file model.cc.
References DIM, Species::Specie::Mass(), Species::nspecies, REAL, SMALL, Species::species, Run::time, type, v, and x.
Referenced by Domain::run().
void Molecule::setCoordinates (REAL y[]) [inline]
Definition at line 112 of file model.h.
References DIM, and x.
void Molecule::setVelocity (REAL u[]) [inline]
Definition at line 130 of file model.h.
References DIM, and v.
void Molecule::Temperature (REAL temperature)
Set internal energy according to temperature:.
Set internal energy according to the temperature.
Parameters:
temperature temperature in K
Definition at line 57 of file model.cc.
References AtomicMassUnit, BoltzmannConstant, Species::Specie::Cp(), DOF, DOFI, energy, InternalEnergy(), REAL, Species::species, and Type().
Referenced by Domain::init(), and Boundary::Inject().
int Molecule::Type () [inline]
Definition at line 50 of file model.h.
References type.
Referenced by Temperature().
void Molecule::Type (int t) [inline]
Definition at line 49 of file model.h.
References type.
Referenced by Domain::boundary(), copy(), Gui::display(), Bulk::inject(), Boundary::Inject(), Domain::interact(), Domain::interaction(), Domain::load(), GridContainer::put(), Domain::run(), and Domain::save().
void Molecule::Velocity (REAL u[]) [inline]
Definition at line 129 of file model.h.
References DIM, and v.
REAL* Molecule::Velocity () [inline]
Definition at line 128 of file model.h.
References v.
void Molecule::Velocity (int i, REAL u) [inline]
Definition at line 121 of file model.h.
References DIM, and v.
REAL Molecule::Velocity (int i) [inline]
Definition at line 113 of file model.h.
References DIM, and v.
Referenced by Domain::boundary(), copy(), Bulk::inject(), Boundary::Inject(), Domain::interact(), Domain::load(), GridContainer::put(), Domain::run(), and Domain::save().
Member Data Documentation
REAL Molecule::energy [private]
internal energy
Definition at line 40 of file model.h.
Referenced by InternalEnergy(), Molecule(), and Temperature().
int Molecule::type [private]
points to the species[type];
Definition at line 24 of file model.h.
Referenced by copy(), KineticEnergy(), Molecule(), Move(), and Type().
REAL Molecule::v[DIM] [private]
velocity of center of mass
Definition at line 40 of file model.h.
Referenced by copy(), KineticEnergy(), Move(), setVelocity(), and Velocity().
REAL Molecule::x[DIM] [private]
position of center of mass
Definition at line 40 of file model.h.
Referenced by Coordinate(), Coordinates(), copy(), Move(), and setCoordinates().
The documentation for this class was generated from the following files:
model.h
model.cc