ReMoDy: job.cc File Reference
job.cc File Reference
The ReMoDy backend.
#include <string.h>
#include <cstdlib>
#include <iostream>
#include <libxml/xmlmemory.h>
#include <libxml/parser.h>
#include <math.h>
#include "def.h"
#include "io.h"
#include "run.h"
#include "list.h"
#include "collection.h"
#include "model.h"
#include "species.h"
#include "domain.h"
Functions
void usage ()
void parsename (char *name, char *filename)
Strips the suffix from the filename.
int main (int argc, char *argv[])
The Main routine for a batch mode. Executes a background job.
Detailed Description
The ReMoDy backend.
Executes background job.
Definition in file job.cc.
Function Documentation
int main (int argc, char * argv[])
The Main routine for a batch mode. Executes a background job.
Parameters:
argc,argv,: standard command line arguments
Returns:
exit code 0 - success, 1 - failure.
parses command line arguments
creates a domain instance
erases screen
runs the code
retrieves taskname
retrieves taskname
saves data
Definition at line 41 of file job.cc.
References Run::configfile, Gui::domain, ESC, IO::getIter(), Run::init(), Run::inputfile, Run::option, parsename(), Run::programname, Domain::run(), Domain::save(), and WORDLENGTH.
void parsename (char * name, char * filename)
Strips the suffix from the filename.
Parameters:
filename,: file name including suffix
Returns:
name: file name with suffix removed
Definition at line 30 of file job.cc.
Referenced by main().
void usage ()
Definition at line 23 of file job.cc.