ReMoDy: Geom Namespace Reference
Geom Namespace Reference
Provides some trigeometry functions.
Functions
void distvec (REAL a[], REAL b[], REAL c[])
REAL distance (REAL a[], REAL b[])
REAL distance (int dim, REAL a[], REAL b[])
REAL sclp (REAL a[], REAL b[])
REAL length (REAL a[])
REAL area (REAL a[], REAL b[])
REAL normalize (REAL a[])
int hash (int i, int j, int n)
Detailed Description
Provides some trigeometry functions.
Function Documentation
REAL Geom::area (REAL a[], REAL b[])
Definition at line 148 of file model.cc.
References DIM, LENGTH, REAL, and VECP.
Referenced by Domain::Domain(), and Domain::injection().
REAL Geom::distance (int dim, REAL a[], REAL b[])
Definition at line 124 of file model.cc.
References REAL.
REAL Geom::distance (REAL a[], REAL b[])
Definition at line 116 of file model.cc.
References DIM, and REAL.
void Geom::distvec (REAL a[], REAL b[], REAL c[])
Definition at line 113 of file model.cc.
References DIM.
int Geom::hash (int i, int j, int n)
Definition at line 137 of file model.cc.
REAL Geom::length (REAL a[])
Definition at line 140 of file model.cc.
References DIM, and REAL.
Referenced by normalize().
REAL Geom::normalize (REAL a[])
Definition at line 108 of file model.cc.
References DIM, length(), and REAL.
REAL Geom::sclp (REAL a[], REAL b[])
Definition at line 132 of file model.cc.
References DIM, and REAL.