ReMoDy: GridContainer Namespace Reference
GridContainer Namespace Reference
Domain Segmentation for Interaction Acceleration.
Functions
void init (REAL ymin[], REAL ymax[], REAL radius, Pool< Molecule > *newpool)
int index (int ind[])
void index (int n, int ind[])
void put (Molecule *node)
void put (Molecule *node, int icounter)
Container< Molecule > * get (int ind[])
int * dimensions ()
bool checkPool (int icell, char *msg)
Variables
REAL xmin [DIM]
REAL xmax [DIM]
REAL cellsize
int ncells [DIM+1]
int mcells = 0
int mcells1 = 0
Container< Molecule > * nodes
Pool< Molecule > * pool
Detailed Description
Domain Segmentation for Interaction Acceleration.
Splits space into cubic cells to consider local interactions between ajacent cells only
Function Documentation
bool GridContainer::checkPool (int icell, char * msg)
int * GridContainer::dimensions ()
Definition at line 181 of file grid.cc.
References ncells.
Container< Molecule > * GridContainer::get (int ind[])
Definition at line 178 of file grid.cc.
References index(), and nodes.
void GridContainer::index (int n, int ind[])
Definition at line 68 of file grid.cc.
References DIM, mcells1, and ncells.
Referenced by Domain::interaction().
int GridContainer::index (int ind[])
Definition at line 61 of file grid.cc.
References DIM, and ncells.
Referenced by get(), and put().
void GridContainer::init (REAL ymin[], REAL ymax[], REAL radius, Pool< Molecule > * newpool)
Definition at line 25 of file grid.cc.
References cellsize, DIM, mcells, mcells1, ncells, nodes, Run::option, pool, REAL, xmax, and xmin.
void GridContainer::put (Molecule * node, int icounter)
DDD
DDD
Definition at line 128 of file grid.cc.
References cellsize, Molecule::Coordinates(), DIM, index(), ncells, nodes, REAL, Molecule::Type(), VOIDSPECIE, and xmin.
Referenced by Domain::Domain(), Boundary::Inject(), and Domain::run().
void GridContainer::put (Molecule * node)
Definition at line 81 of file grid.cc.
References cellsize, Molecule::Coordinates(), DIM, index(), ncells, nodes, REAL, Species::species, Run::time, Molecule::Type(), Molecule::Velocity(), VOIDSPECIE, and xmin.
Variable Documentation
REAL GridContainer::cellsize
Definition at line 20 of file grid.cc.
Referenced by Domain::Domain(), init(), put(), and Domain::run().
int GridContainer::mcells = 0
Definition at line 22 of file grid.cc.
Referenced by init().
int GridContainer::mcells1 = 0
Definition at line 22 of file grid.cc.
Referenced by index(), and init().
int GridContainer::ncells
Definition at line 21 of file grid.cc.
Referenced by dimensions(), index(), init(), Domain::interaction(), and put().
Container< Molecule > * GridContainer::nodes
Definition at line 23 of file grid.cc.
Referenced by get(), init(), put(), and Domain::run().
Pool< Molecule > * GridContainer::pool
Definition at line 24 of file grid.cc.
Referenced by Container< Element >::append0(), init(), Container< Element >::insert0(), and Container< Element >::remove0().
REAL GridContainer::xmax[DIM]
Definition at line 19 of file grid.cc.
Referenced by init().
REAL GridContainer::xmin[DIM]
Definition at line 19 of file grid.cc.
Referenced by init(), and put().