ReMoDy: view.cc File Reference
view.cc File Reference
The frontend of ReMoDy with the OpenGL Visualizer.
#include <iostream>
#include <libxml/xmlmemory.h>
#include <libxml/parser.h>
#include <math.h>
#include "def.h"
#include "run.h"
#include "list.h"
#include "collection.h"
#include "grid.h"
#include "container.h"
#include "model.h"
#include "species.h"
#include "domain.h"
#include "gui.h"
Functions
void usage ()
int main (int argc, char *argv[])
The main routine.
Detailed Description
The frontend of ReMoDy with the OpenGL Visualizer.
Executes a job and displays the computational domain in an OpenGL window.
Definition in file view.cc.
Function Documentation
int main (int argc, char * argv[])
The main routine.
parses command line arguments
creates a domain instance
initializes the domain
executes the job
Definition at line 29 of file view.cc.
References Gui::domain, Gui::init(), Run::init(), Run::inputfile, and Gui::run().
void usage ()
Definition at line 25 of file view.cc.
References Run::programname.